# Package Info.
set(CURL_NAME "Curl")
set(CURL_DESCRIPTION "A command-line tool used to transfer data from or to a server using various protocols such as HTTP, FTP, SMTP, etc. It is widely used in the development of web applications to test APIs or interact with web servers.")

# Pakcage option.
option(USE_CURL ${CURL_DESCRIPTION} TRUE)
if (USE_CURL)
    add_definitions(-DUSE_CURL)
endif()

if(USE_CURL)
    # Search Curl
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_search_module(CURL QUIET libcurl curl)
    endif()

    if(NOT CURL_FOUND)
        find_path(CURL_INCLUDE_DIR NAMES curl/curl.h)
        find_library(CURL_LIBRARY NAMES curl libcurl)
        if(CURL_INCLUDE_DIR AND CURL_LIBRARY)
            set(CURL_FOUND TRUE)
            set(CURL_INCLUDE_DIRS "${CURL_INCLUDE_DIR}")
            get_filename_component(CURL_LIBRARY_DIRS "${CURL_LIBRARY}" DIRECTORY)
            set(CURL_LINK_LIBRARIES "${CURL_LIBRARY}")
        endif()
    endif()

    if(CURL_FOUND)
        message(STATUS "Using Curl ${CURL_VERSION}")
        list(APPEND LIB_MODULES ${CURL_LINK_LIBRARIES})
        list(APPEND LIB_TARGET_INCLUDE_DIRECTORIES ${CURL_INCLUDE_DIRS})
        list(APPEND LIB_TARGET_LIBRARY_DIRECTORIES ${CURL_LIBRARY_DIRS})
        list(APPEND LIB_TARGET_LINK_DIRECTORIES ${CURL_LIBRARY_DIRS})
        list(APPEND LIB_TARGET_COMPILER_DEFINATION "")
    else()
        message(WARNING "Curl was requested but no curl package was detected.")
    endif()
endif()
if(NOT CURL_FOUND)
    return()
endif()
